### PR TITLE
add bucket to_infinity

### PR DESCRIPTION
**Pull request by ctrlok**
I'm sorry, I forget about that PR https://github.com/go-graphite/carbonzipper/pull/18

So... How about that?

### CODE REVIEW

**Comment by deniszh** [comment]
inf
You have conflicts, though....

**Comment by ctrlok** [comment]
@deniszh LOL

**Comment by Civil** [comment]
Well, if that still matters, I'm planning (eventually) to rethink all exported metrics and then I can either name metrics with some other name or at least add an option to choose how last bucket is named. That shouldn't be hard. So while the PR I won't merge, but functionality eventually will be there.

**Comment by ctrlok** [comment]
It's not urgent anyway haha

**Pull request closed without merging**
